import json
import os

# Complete alias mapping for all characters
ALIASES = {
    # ---- ANIME ----
    "Son Goku": ["Goku", "Kakarot"],
    "Naruto Uzumaki": ["Naruto"],
    "Monkey D. Luffy": ["Luffy", "Straw Hat"],
    "Satoru Gojo": ["Gojo"],
    "Levi Ackerman": ["Levi", "Captain Levi"],
    "Saitama": ["One Punch Man", "Caped Baldy"],
    "Edward Elric": ["Ed", "Fullmetal Alchemist"],
    "Light Yagami": ["Light", "Kira"],
    "Lelouch Lamperouge": ["Lelouch", "Zero"],
    "Killua Zoldyck": ["Killua"],
    "Tanjiro Kamado": ["Tanjiro"],
    "Izuku Midoriya": ["Deku", "Midoriya"],
    "Roronoa Zoro": ["Zoro", "Pirate Hunter"],
    "Kakashi Hatake": ["Kakashi", "Copy Ninja"],
    "Vegeta": ["Prince Vegeta"],
    "Eren Yeager": ["Eren", "Attack Titan"],
    "Gon Freecss": ["Gon"],
    "Yuji Itadori": ["Itadori"],
    "Natsu Dragneel": ["Natsu", "Salamander"],
    "Ichigo Kurosaki": ["Ichigo"],
    "Sosuke Aizen": ["Aizen"],
    "Shoto Todoroki": ["Shoto", "Todoroki"],
    "Nezuko Kamado": ["Nezuko"],
    "Spike Spiegel": ["Spike"],
    "Shinji Ikari": ["Shinji"],
    "Mob (Shigeo Kageyama)": ["Mob", "Shigeo"],
    "Ryomen Sukuna": ["Sukuna", "King of Curses"],
    "Mikasa Ackerman": ["Mikasa"],
    "Sasuke Uchiha": ["Sasuke"],
    "Alucard": ["Alucard"],
    "Yusuke Urameshi": ["Yusuke"],
    "Gohan": ["Gohan"],
    "Roy Mustang": ["Roy", "Mustang", "Flame Alchemist"],
    "L Lawliet": ["L", "Ryuzaki"],
    "Erza Scarlet": ["Erza", "Titania"],
    "Ken Kaneki": ["Kaneki", "Centipede"],
    "Rimuru Tempest": ["Rimuru", "Slime"],
    "Sung Jinwoo": ["Jinwoo", "Solo Leveling"],
    "Asuka Langley Soryu": ["Asuka"],
    "Hisoka Morow": ["Hisoka"],
    "Madara Uchiha": ["Madara"],
    "Sanji": ["Sanji", "Black Leg"],
    "Katsuki Bakugo": ["Bakugo", "Kacchan"],
    "Zenitsu Agatsuma": ["Zenitsu"],
    "Megumi Fushiguro": ["Megumi"],
    "Meliodas": ["Meliodas"],
    "Saber": ["Saber", "Artoria"],
    "Kurapika": ["Kurapika"],
    "Sesshomaru": ["Sesshomaru"],
    "Ash Ketchum": ["Ash", "Satoshi"],
    "Guts": ["Guts", "Black Swordsman"],
    "Denji": ["Denji", "Chainsaw Man"],
    "Miyamoto Musashi": ["Musashi", "Vagabond"],
    "Thorfinn Karlsefni": ["Thorfinn"],
    "Jotaro Kujo": ["Jotaro"],
    "Johan Liebert": ["Johan"],
    "Makima": ["Makima", "Control Devil"],
    "Dio Brando": ["Dio"],
    "Griffith": ["Griffith", "Femto"],
    "Aqua Hoshino": ["Aqua"],
    "Yoichi Isagi": ["Isagi"],
    "Shoyo Hinata": ["Hinata"],
    "Gabimaru": ["Gabimaru"],
    "Shin": ["Shin"],
    "Power": ["Power"],
    "Joseph Joestar": ["Joseph"],
    "Aki Hayakawa": ["Aki"],
    "Punpun Onodera": ["Punpun"],
    "Friend": ["Friend"],
    "Kenji Endo": ["Kenji"],
    "Askeladd": ["Askeladd"],
    "Tobio Kageyama": ["Kageyama"],
    "Seishiro Nagi": ["Nagi"],
    "Sano Manjiro (Mikey)": ["Mikey", "Manjiro"],
    "Takemichi Hanagaki": ["Takemichi"],
    "Chihiro Rokuhira": ["Chihiro"],
    "Rudo": ["Rudo"],
    "Momo Ayase": ["Momo"],
    "Okarun (Ken Takakura)": ["Okarun", "Ken Takakura"],
    "Maomao": ["Maomao"],
    "Frieren": ["Frieren"],
    "Himmel": ["Himmel"],
    "Sakamoto Taro": ["Sakamoto"],
    "Nagumo": ["Nagumo"],
    "Mash Burnedead": ["Mash"],
    "Loid Forger": ["Loid", "Twilight"],
    "Anya Forger": ["Anya"],
    "Yor Forger": ["Yor", "Thorn Princess"],
    "Baki Hanma": ["Baki"],
    "Ohma Tokita": ["Ohma", "Ashura"],
    "Tsunayoshi Sawada": ["Tsuna", "Sawada"],
    "Yugi Mutou": ["Yugi"],
    "Seto Kaiba": ["Kaiba"],
    "Allen Walker": ["Allen"],
    "Toriko": ["Toriko"],
    "Rin Okumura": ["Rin"],
    "Asta": ["Asta"],
    "Yami Sukehiro": ["Yami"],
    "Senku Ishigami": ["Senku"],
    "Clare": ["Clare"],
    
    # ---- DC ----
    "Superman": ["Clark Kent", "Kal-El"],
    "Batman": ["Bruce Wayne", "Dark Knight"],
    "Wonder Woman": ["Diana Prince", "Diana"],
    "The Joker": ["Joker", "Jack Napier"],
    "The Flash": ["Barry Allen", "Flash"],
    "Green Lantern": ["Hal Jordan", "Green Lantern"],
    "Aquaman": ["Arthur Curry", "Orin"],
    "Harley Quinn": ["Harley", "Harleen Quinzel"],
    "Nightwing": ["Dick Grayson"],
    "Robin": ["Tim Drake", "Robin"],
    "Red Hood": ["Jason Todd"],
    "Lex Luthor": ["Lex"],
    "Catwoman": ["Selina Kyle"],
    "Shazam": ["Billy Batson", "Captain Marvel"],
    "Black Adam": ["Black Adam", "Teth-Adam"],
    "Green Arrow": ["Oliver Queen", "Ollie"],
    "Cyborg": ["Victor Stone"],
    "Raven": ["Raven"],
    "Beast Boy": ["Garfield Logan", "Gar"],
    "Starfire": ["Koriand'r", "Kory"],
    "Supergirl": ["Kara Zor-El", "Kara"],
    "Batgirl": ["Barbara Gordon", "Babs"],
    "Darkseid": ["Darkseid"],
    "Brainiac": ["Brainiac"],
    "Deathstroke": ["Slade Wilson"],
    "The Riddler": ["Edward Nygma", "Riddler"],
    "Penguin": ["Oswald Cobblepot"],
    "Two-Face": ["Harvey Dent"],
    "Bane": ["Bane"],
    "Poison Ivy": ["Ivy", "Pamela Isley"],
    "Scarecrow": ["Jonathan Crane"],
    "Martian Manhunter": ["J'onn J'onzz", "Manhunter"],
    "John Constantine": ["Constantine"],
    "Zatanna": ["Zatanna"],
    "Swamp Thing": ["Swamp Thing"],
    "The Flash (Wally West)": ["Wally West", "Kid Flash"],
    "Green Lantern (John Stewart)": ["John Stewart"],
    "Sinestro": ["Sinestro"],
    "Reverse-Flash": ["Eobard Thawne", "Reverse Flash"],
    "Black Canary": ["Dinah Lance", "Canary"],
    "Hawkman": ["Katar Hol"],
    "Hawkgirl": ["Shayera Hol"],
    "Doctor Fate": ["Kent Nelson", "Fate"],
    "Blue Beetle": ["Jaime Reyes"],
    "Booster Gold": ["Michael Carter"],
    "Lobo": ["Lobo"],
    "Ra's al Ghul": ["Ra's", "Demon's Head"],
    "Talia al Ghul": ["Talia"],
    "Amanda Waller": ["Waller"],
    "General Zod": ["Zod"],
    
    # ---- MARVEL ----
    "Spider-Man": ["Spider Man", "Spidey", "Peter Parker"],
    "Iron Man": ["Tony Stark", "Shellhead"],
    "Captain America": ["Steve Rogers", "Cap"],
    "Thor": ["Thor", "God of Thunder"],
    "The Hulk": ["Hulk", "Bruce Banner"],
    "Black Widow": ["Natasha Romanoff", "Nat"],
    "Wolverine": ["Logan", "James Howlett"],
    "Deadpool": ["Wade Wilson", "Merc with a Mouth"],
    "Doctor Strange": ["Stephen Strange", "Strange"],
    "Black Panther": ["T'Challa"],
    "Star-Lord": ["Peter Quill"],
    "Groot": ["Groot"],
    "Rocket Raccoon": ["Rocket"],
    "Thanos": ["Thanos"],
    "Loki": ["Loki", "God of Mischief"],
    "Scarlet Witch": ["Wanda Maximoff", "Wanda"],
    "Vision": ["Vision"],
    "Hawkeye": ["Clint Barton"],
    "Falcon": ["Sam Wilson"],
    "Winter Soldier": ["Bucky Barnes", "Bucky"],
    "Ant-Man": ["Scott Lang"],
    "Captain Marvel": ["Carol Danvers"],
    "Venom": ["Venom", "Eddie Brock"],
    "Carnage": ["Cletus Kasady"],
    "Green Goblin": ["Norman Osborn"],
    "Doctor Octopus": ["Doc Ock", "Otto Octavius"],
    "Magneto": ["Magneto", "Erik Lehnsherr"],
    "Professor X": ["Charles Xavier", "Xavier"],
    "Cyclops": ["Scott Summers"],
    "Jean Grey": ["Jean", "Phoenix"],
    "Storm": ["Ororo Munroe"],
    "Rogue": ["Rogue", "Anna Marie"],
    "Gambit": ["Remy LeBeau"],
    "Daredevil": ["Matt Murdock"],
    "The Punisher": ["Frank Castle"],
    "Kingpin": ["Wilson Fisk"],
    "Moon Knight": ["Marc Spector"],
    "Ghost Rider": ["Johnny Blaze"],
    "Blade": ["Blade", "Eric Brooks"],
    "Silver Surfer": ["Norrin Radd"],
    "Galactus": ["Galactus"],
    "Doctor Doom": ["Victor Von Doom", "Doom"],
    "Miles Morales": ["Miles"],
    "Spider-Gwen": ["Gwen Stacy", "Spider Gwen"],
    "Cable": ["Cable", "Nathan Summers"],
    "Mystique": ["Raven Darkhölme"],
    "Nightcrawler": ["Kurt Wagner"],
    "Shang-Chi": ["Shang Chi", "Shaun"],
    "Ms. Marvel": ["Kamala Khan"],
    "Nick Fury": ["Fury"],
    
    # ---- GAMING ----
    "Mario": ["Mario", "Jumpman"],
    "Pikachu": ["Pika"],
    "Sonic the Hedgehog": ["Sonic", "Blue Blur"],
    "Link": ["Link", "Hero of Hyrule"],
    "Master Chief": ["Chief", "John-117"],
    "Kratos": ["Kratos", "Ghost of Sparta"],
    "Cloud Strife": ["Cloud"],
    "Solid Snake": ["Snake"],
    "Lara Croft": ["Lara"],
    "Steve": ["Steve", "Minecraft Steve"],
    "Geralt of Rivia": ["Geralt", "White Wolf"],
    "Arthur Morgan": ["Arthur"],
    "Nathan Drake": ["Nate", "Drake"],
    "Ezio Auditore da Firenze": ["Ezio"],
    "Leon S. Kennedy": ["Leon"],
    "Doomguy / Doom Slayer": ["Doomguy", "Doom Slayer"],
    "Samus Aran": ["Samus"],
    "Ryu": ["Ryu"],
    "Scorpion": ["Scorpion", "Hanzo Hasashi"],
    "Sub-Zero": ["Kuai Liang"],
    "Pac-Man": ["Pacman", "Pac"],
    "Sans": ["Sans"],
    "Ellie": ["Ellie"],
    "Joel Miller": ["Joel"],
    "Sephiroth": ["Sephiroth"],
    "Donkey Kong": ["DK"],
    "Bowser": ["Bowser", "King Koopa"],
    "Princess Peach": ["Peach"],
    "Luigi": ["Luigi", "Green Mario"],
    "Crash Bandicoot": ["Crash"],
    "Spyro the Dragon": ["Spyro"],
    "Agent 47": ["47"],
    "Commander Shepard": ["Shepard"],
    "Garrus Vakarian": ["Garrus"],
    "Ciri": ["Ciri", "Cirilla"],
    "John Marston": ["John"],
    "Gordon Freeman": ["Gordon", "Freeman"],
    "GLaDOS": ["GLaDOS"],
    "Chell": ["Chell"],
    "Chun-Li": ["Chun Li", "Chun"],
    "Dante": ["Dante"],
    "Vergil": ["Vergil"],
    "Niko Bellic": ["Niko"],
    "Trevor Philips": ["Trevor"],
    "CJ (Carl Johnson)": ["CJ", "Carl Johnson"],
    "Marcus Fenix": ["Marcus"],
    "Sylvanas Windrunner": ["Sylvanas"],
    "Illidan Stormrage": ["Illidan"],
    "Shadowheart": ["Shadowheart"],
    "Astarion": ["Astarion"],
}

def add_aliases_to_file(filename):
    if not os.path.exists(filename):
        print(f"⚠️ File not found: {filename}")
        return
    with open(filename, 'r', encoding='utf-8') as f:
        data = json.load(f)
    updated = 0
    for entry in data:
        name = entry.get('name', '')
        if name in ALIASES:
            entry['aliases'] = ALIASES[name]
            updated += 1
        else:
            if 'aliases' not in entry:
                entry['aliases'] = []
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"✅ Updated {filename}: added aliases to {updated} entries")

if __name__ == "__main__":
    files = [
        "characters_anime_db.json",
        "characters_dc_db.json",
        "characters_marvel_db.json",
        "characters_gaming_db.json"
    ]
    for f in files:
        add_aliases_to_file(f)
    print("🎉 All done! Aliases have been added to your character databases.")